# Generated by Django 3.0 on 2022-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=80)),
                ('bprice', models.IntegerField()),
                ('bauthor', models.CharField(max_length=120)),
                ('bdesc', models.CharField(max_length=200)),
            ],
        ),
    ]
